name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - main-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Model
        run: echo "Building model"

      - name: Run Tests
        run: echo "Running tests"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Model
        run: echo "Deploying model to production"
